name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install ESLint and plugins
        run: npm install eslint@8 eslint-plugin-html@8 --no-save

      - name: Run ESLint
        run: npx eslint . --ext .js,.html

      - name: Run unit tests
        run: npm test
